- app/helpers/api/v1/payments_helper.rb
- app/helpers/balances_helper.rb
- app/helpers/buda_authentications_helper.rb
- app/helpers/payments_helper.rb
- spec/helpers/api/v1/payments_helper_spec.rb
- spec/helpers/api/v1/quotations_helper_spec.rb
- spec/models/user_spec.rb
Habían varios tests fallando por archivos que cambiamos de lugar/nombre y otros que eliminamos de los auto generados.
Con esto se arregla eso y queda el boilerplate listo por si se quieren agregar tests a estos controladores en el futuro.
> [backend] fix: auto generated tests

- app/controllers/api/v1/users_controller.rb
- spec/requests/user_request_spec.rb
Unit tests for CRUD of users and fix of update endopoint
Todos los tests de los endpoints están `200: OK`
> [Backend] Unit tests for CRUD of users

- app/javascript/router/SignUp.vue
> [web] del: buda user input field SignUp

- .env.development
- Gemfile
- Gemfile.lock
- app/controllers/api/v1/splitwise_controller.rb
- app/helpers/api/v1/splitwise_helper.rb
- app/models/user.rb
- app/services/splitwise_service.rb
- app/views/api/v1/splitwise/create.json.jbuilder
- config/initializers/inflections.rb
- config/routes.rb
- config/secrets.yml
- db/migrate/20200419202307_add_splitwise_token_to_user.rb
- db/migrate/20200419225059_add_oauth_token_to_user.rb
- db/migrate/20200419225124_add_oauth_secret_to_user.rb
- db/migrate/20200419230248_add_splitwise_secret_to_user.rb
- db/schema.rb
- spec/helpers/api/v1/splitwise_helper_spec.rb
- spec/requests/api/v1/splitwise_request_spec.rb
- spec/services/splitwise_service_spec.rb
- Auth for Splitwise with OAuth
- SplitWise service that can be reused in other controllers to make use of the api easily 
- Encryption of Splitwise information in user model
> [backend]: Splitwise api integration

- app/javascript/components/Input.vue
- app/javascript/components/navBar.vue
- app/javascript/router/Payment.vue
- app/javascript/router/index.js
> [web] Payment UI

- app/javascript/app.spec.js
- app/javascript/components/InputLabel.vue
- app/javascript/components/__tests__/BudaAlert.spec.js
- app/javascript/components/__tests__/BudaForm.spec.js
- app/javascript/components/__tests__/BudaIndex.spec.js
- app/javascript/components/__tests__/BudaLogoutForm.spec.js
- app/javascript/components/__tests__/Input.spec.js
- app/javascript/components/__tests__/InputLabel.spec.js
- app/javascript/components/__tests__/PasswordInput.spec.js
- app/javascript/components/__tests__/SubmitButton.spec.js
- app/javascript/components/__tests__/__snapshots__/BudaAlert.spec.js.snap
- app/javascript/components/__tests__/__snapshots__/BudaForm.spec.js.snap
- app/javascript/components/__tests__/__snapshots__/BudaIndex.spec.js.snap
- app/javascript/components/__tests__/__snapshots__/BudaLogoutForm.spec.js.snap
- app/javascript/components/__tests__/__snapshots__/Input.spec.js.snap
- app/javascript/components/__tests__/__snapshots__/InputLabel.spec.js.snap
- app/javascript/components/__tests__/__snapshots__/PasswordInput.spec.js.snap
- app/javascript/components/__tests__/__snapshots__/SubmitButton.spec.js.snap
- app/javascript/router/__tests__/Landing.spec.js
- app/javascript/router/__tests__/SignIn.spec.js
- app/javascript/router/__tests__/SignUp.spec.js
- app/javascript/router/__tests__/__snapshots__/Landing.spec.js.snap
- app/javascript/router/__tests__/__snapshots__/SignIn.spec.js.snap
- app/javascript/router/__tests__/__snapshots__/SignUp.spec.js.snap
- package.json
Agregué varios test de snapshots bien básicos pero que ayudan a encontrar errores no intencionados donde estamos quizás cambiando código de otras personas en consecuencia de nuestros cambios.
> [web] Added snapshot tests

- spec/requests/user_request_spec.rb
Agregue más it statements de tal forma que fueran más legibles los tests.
También reduje el codigo repetido usando before(:each) y estructure los tests de tal forma que cada uno fuese independiente (antes habían expects que dependían de los expects anteriores).
> [backend] tests: refactored user CRUD tests

- app/javascript/components/BudaForm.vue
- app/javascript/components/BudaIndex.vue
- app/javascript/components/BudaLogoutForm.vue
- app/javascript/components/SubmitButton.vue
- app/javascript/components/TextField.vue
- app/javascript/components/__tests__/__snapshots__/BudaForm.spec.js.snap
- app/javascript/components/__tests__/__snapshots__/BudaIndex.spec.js.snap
- app/javascript/components/__tests__/__snapshots__/BudaLogoutForm.spec.js.snap
- app/javascript/components/__tests__/__snapshots__/SubmitButton.spec.js.snap
- app/javascript/components/navBar.vue
- app/javascript/router/Home.vue
- app/javascript/router/Payment.vue
- app/javascript/store/modules/user/actions.js
- app/javascript/store/modules/user/mutations.js
Se estructuró los componentes de acuerdo a lo pedido en el último PR. Se agregaron dos caminos para manejar los dos tipos de errores que pueden recibirse en las distintas acciones. Se arregló el envío de pagos.
> [web] refactor/fix: components, errors handle and payments

- app/serializers/api/v1/user_serializer.rb
- app/services/splitwise_service.rb
Get user picture from Splitwise API and return the 3 different sizes (small, medium and large)
> [backend] user picture from api

- .env.development
- app/controllers/api/v1/splitwise/debts_controller.rb
- app/helpers/api/v1/splitwise/debts_helper.rb
- app/views/api/v1/splitwise/debts/show.json.jbuilder
- Hace una request a la API de Splitwise para obtener todas las deudas del usuario que el debe o le deben. 
- Retorna dos listas una con las deudas que yo debo y otra con las deudas que me deben.
> [backend]feat: endpoint to get splitwise debts

- app/javascript/router/Home.vue
Se muestran las transacciones dejando la fecha más reciente arriba.
> [web] fix: reverse order of transactions

- app/javascript/components/navBar.vue
- app/javascript/router/Home.vue
- app/javascript/router/Payment.vue
- app/javascript/router/SignIn.vue
- app/javascript/router/SignUp.vue
- app/javascript/router/__tests__/__snapshots__/SignIn.spec.js.snap
- app/javascript/router/__tests__/__snapshots__/SignUp.spec.js.snap
Se corrige el idioma del header, tabla de historial de transacciones y botones. Se pasa de inglés a español.
> [web] fix: change language

- app/javascript/components/BudaForm.vue
- app/javascript/components/PaymentConfirm.vue
- app/javascript/components/SubmitButton.vue
- app/javascript/components/UserCard.vue
- app/javascript/components/__tests__/BudaForm.spec.js
- app/javascript/components/__tests__/__snapshots__/SubmitButton.spec.js.snap
- app/javascript/router/Home.vue
- app/javascript/store/modules/user/actions.js
- app/javascript/store/modules/user/mutations.js
- app/javascript/store/modules/user/state.js
Se agregó la verificación de las credenciales Buda al momento de intentar asociar una cuenta. Se lanza un error si están no son correctas. 
Se hicieron pequeñas correcciones de estilo.
> [web] feat: check buda keys

- .env.development
- app/controllers/api/v1/splitwise/debts_controller.rb
- app/helpers/api/v1/splitwise/debts_helper.rb
- app/services/splitwise_service.rb
- Antes no se tenía la información de todos los amigos del usuario para retornarla si había una deuda con alguno. 
- Lo arreglé haciendo una request a la API de Splitwise que retorna todos los amigos del usuario.
- Reviso cada deuda y a partir de los id de los usuarios from y to, busco su información en la lista que obtuve de Splitwise.
> [backend] fix: get info all friends

- app/controllers/api/v1/balances_controller.rb
- app/controllers/api/v1/firebase_controller.rb
- app/controllers/api/v1/payments_controller.rb
- app/controllers/api/v1/quotations_controller.rb
- app/controllers/api/v1/sessions_controller.rb
- app/controllers/api/v1/splitwise/authentications_controller.rb
- app/controllers/api/v1/splitwise/debts_controller.rb
- app/controllers/api/v1/users_controller.rb
- app/controllers/application_controller.rb
- app/controllers/concerns/token_authenticatable.rb
- app/controllers/home_controller.rb
- app/helpers/api/v1/splitwise/debts_helper.rb
- app/models/payment.rb
- app/models/user.rb
- app/serializers/api/v1/payment_serializer.rb
- app/serializers/api/v1/user_serializer.rb
- app/services/buda_user_service.rb
- app/services/firebase_service.rb
- app/services/payments_service.rb
- app/services/splitwise_service.rb
- bin/rubocop-check.bash
Corrección de estilo de los archivos para adherirse a `rubocop`
> Rubocop 💎👮🏽‍♂️

- app/javascript/components/BudaForm.vue
- app/javascript/components/BudaIndex.vue
- app/javascript/components/BudaLogoutForm.vue
- app/javascript/components/BudaOnBoarding.vue
- app/javascript/components/CurrentStep.vue
- app/javascript/components/SplitwiseOnBoarding.vue
- app/javascript/components/StepButton.vue
- app/javascript/components/SubmitButton.vue
- app/javascript/components/__tests__/__snapshots__/BudaIndex.spec.js.snap
- app/javascript/components/__tests__/__snapshots__/BudaLogoutForm.spec.js.snap
- app/javascript/components/__tests__/__snapshots__/PasswordInput.spec.js.snap
- app/javascript/router/BudaIndex.vue
- app/javascript/router/OnBoarding.vue
- app/javascript/router/SignUp.vue
- app/javascript/router/index.js
- app/javascript/store/action-types.js
- app/javascript/store/index.js
- app/javascript/store/modules/onBoarding/index.js
- app/javascript/store/mutation-types.js
- app/views/home/index.html.erb
- app/views/layouts/application.html.erb
- package.json
- svgTransform.js
Agrega pantalla de onboarding, que se redirige justo despues de crear una cuenta. Incluye las opciones para linkear la cuenta con buda y con splitwise.
> On boarding

- app/commands/convert_satoshis_to_bitcoins.rb
- app/controllers/api/v2/balances_controller.rb
- app/helpers/api/v2/balances_helper.rb
- app/views/api/v2/balances/error.json.jbuilder
- app/views/api/v2/balances/show.json.jbuilder
- config/routes.rb
- Endpoint de API/V2 para ver el saldo del usuario en buda y en bistplit (opennode).
- Hace una request a Buda para obtener el saldo del usuario en esta plataforma.
- Llama es balances_helper que es el que va a preparar la respuesta.
> [backend] feat: bitsplit balance endpoint

- app/controllers/api/v2/transfers_controller.rb
- app/services/money_service.rb
Si se que está horrible la función payment jajajaj y que tengo q crear mil funciones chicas más pero quería que Nacho me revisara si esta es la lógica que quería
> cambio de lógica de transferencias

- app/javascript/components/SubmitButton.vue
- app/javascript/components/__tests__/__snapshots__/SubmitButton.spec.js.snap
- app/javascript/css/application.css
Agrega el orden de imports para que se visualizen correctamente los colores y tamaños secundarios en componentes como botones y textos
> [web]fix: secondary color in button and text workinh

- app/javascript/api/user.js
- app/javascript/api/wallet.js
- app/javascript/components/BudaAlert.vue
- app/javascript/components/BudaForm.vue
- app/javascript/components/Input.vue
- app/javascript/components/LinkButton.vue
- app/javascript/components/Select.vue
- app/javascript/components/SubmitButton.vue
- app/javascript/components/TextField.vue
- app/javascript/components/UserCard.vue
- app/javascript/components/__tests__/__snapshots__/BudaAlert.spec.js.snap
- app/javascript/components/__tests__/__snapshots__/Input.spec.js.snap
- app/javascript/components/__tests__/__snapshots__/SubmitButton.spec.js.snap
- app/javascript/components/navBar.vue
- app/javascript/components/profile/ProfileHome.vue
- app/javascript/components/profile/ProfileOpenNode.vue
- app/javascript/components/profile/ProfileSettings.vue
- app/javascript/components/profile/SplitwiseLink.vue
- app/javascript/css/application.css
- app/javascript/router/Home.vue
- app/javascript/router/Profile.vue
- app/javascript/router/SignIn.vue
- app/javascript/router/SignUp.vue
- app/javascript/router/index.js
- app/javascript/store/action-types.js
- app/javascript/store/modules/user/actions.js
- app/javascript/store/modules/user/mutations.js
- app/javascript/store/modules/user/state.js
Agrega funcionalidad para cargar y sacar plata de tu cuenta de bitsplit (Api todavia no esta funcionando, pero se dejo con los ejemplos y listo para actualizar a la api cuando este)
También actualiza el balance a su v2. Plata en Buda y plata en bitsplit
> Opennode charges

- app/controllers/api/v2/charges_controller.rb
- app/controllers/api/v2/withdrawals_controller.rb
agregué lo de ledgerizer al endpoint de withdrawals y aproveche de borrar unas lineas comentadas del endpoint de charges que se me habia olvidado borrar
> [backend] add ledgerizer registration to withdrawals endpoint

- app/controllers/api/v2/depositwebhooks_controller.rb
Es un cambio muy chico, pero se me habia olvidado excluir el webhook de la autenticación :(
> Depositwebhook fix

- app/controllers/api/v2/transfers_controller.rb
- app/views/api/v2/transfers/create.json.jbuilder
- app/views/api/v2/transfers/error.json.jbuilder
es un cambio chico, faltaba agregar las views para mostrar las respuestas
> Add specific responses to transfers endpoint

- app/controllers/api/v2/buda_pays_controller.rb
- app/services/money_service.rb
- app/views/api/v2/buda_pays/create.json.jbuilder
- config/routes.rb
-  Crea un endpoint para pagar invoices con Buda. 
-  Hace una request a la API de Buda para pagar el invoice de Lightning Network
> Pay buda invoice

- Gemfile
- Gemfile.lock
- Procfile
- app/services/ledgerizer_service.rb
- app/services/money_service.rb
- bin/delayed_job
- config/application.rb
- db/migrate/20200615233016_create_delayed_jobs.rb
- db/schema.rb
- Implementa la gema delayed jobs para manejar las colas de los jobs Deposit, Transfer y Withdrawal.
> Ledgerizer queues

- Procfile
- Arregla un comando del procfile
> [backend] fix: procfile

- app/controllers/api/v2/withdrawals_controller.rb
- app/services/money_service.rb
- app/services/open_node_service.rb
agregué la validación del monto a transferir o retirar (que no sea negativo ni que sea mayor al saldo del usuario)
> Add amount validation to transfers and withdrawals

- app/controllers/api/v1/users_controller.rb
- app/serializers/api/v1/user_serializer.rb
- db/migrate/20200621031722_add_columns_to_user.rb
- db/schema.rb
Se agregan nuevos campos al modelo de usuario (opcionales)
> [backend] add: extra user info

- app/controllers/api/v1/splitwise/debts_controller.rb
- app/views/api/v1/splitwise/debts/create.json.jbuilder
sacamos el pago de la deuda en el controlador porque al final lo vamos a ser aparte
> sacar el pago de deudas de splitwise_controller

- app/javascript/components/NavBarNotifications.vue
- app/javascript/components/ProfileCard.vue
- app/javascript/components/alerts/errorAlert.vue
- app/javascript/components/alerts/successAlert.vue
- app/javascript/components/navBar.vue
- app/javascript/components/profile/ProfileSettings.vue
- app/javascript/router/Profile.vue
Se cambian los iconos importados directamente para usar Material Design Icons. 
En el perfil se agregó la imagen de Splitwise.
> [web] Svg refactor

- app/javascript/api/user.js
- app/javascript/components/navBar.vue
- app/javascript/helpers/index.js
- app/javascript/router/NewPassword.vue
- app/javascript/router/RecoverAccount.vue
- app/javascript/router/SignIn.vue
- app/javascript/router/index.js
- app/javascript/store/action-types.js
- app/javascript/store/modules/user/actions.js
Agrega la funcionalidad (sin integracion con el backend) para recuperar contraseña y  crear una nueva cuenta cuando te mandan plata y no estas registrado en la aplicacion.
> Recover new account

- Gemfile
- Gemfile.lock
- Procfile
- app/controllers/api/v1/users_controller.rb
- app/controllers/api/v2/reset_passwords_controller.rb
- app/controllers/api/v2/transfers_controller.rb
- app/mailers/application_mailer.rb
- app/mailers/user_mailer.rb
- app/services/notifications_service.rb
- app/services/reset_password_service.rb
- app/services/unregistered_user_service.rb
- app/views/api/v2/reset_passwords/create.json.jbuilder
- app/views/api/v2/reset_passwords/update.json.jbuilder
- app/views/user_mailer/password_recovered.html.erb
- app/views/user_mailer/payment_email.html.erb
- app/views/user_mailer/recover_email.html.erb
- app/views/user_mailer/recover_password.html.erb
- app/views/user_mailer/unregistered_email.html.erb
- app/views/user_mailer/welcome_email.html.erb
- config/environments/development.rb
- config/environments/production.rb
- config/initializers/devise.rb
- config/routes.rb
- db/schema.rb
- spec/services/unregistered_user_service_spec.rb
Se integraron y probaron las siguientes funcionalidades:
-Mail de bienvenida
-Mail de recuperar constraseña
-Mail de pago a usuario no registrado
-Mail de pago a usuario registrado
-Mail de contraseña recuperada
> [backend] feat: Unregistered user + Recover Password + Mailer

- app/controllers/api/v1/users_controller.rb
- app/javascript/components/DatePicker.vue
- app/javascript/components/UserInfoOnboarding.vue
- app/javascript/components/profile/ProfileSettings.vue
Se corrigen detalles de la configuración de los datos del usuario. 
Se dejan valores actuales en los formularios.
La función updateCurrentUser se llama solo una vez y si es que no se cambió alguno de los valores se le entrega el valor actual.
> User settings

- .eslintrc.json
- app/javascript/api/user.js
- app/javascript/components/profile/ProfileOpenNode.vue
- app/javascript/store/modules/user/actions.js
Arregla uso del enpoint para sacar plata directamente hacia tu cuenta de buda
Ingresa el verdadero endpoint para recuperar contraseña.
> [web] password recovery and buda direct fix

- app/javascript/components/UserCard.vue
- app/javascript/components/profile/ProfileOpenNode.vue
Agrega spinner para mostrar status de cargando en acciones de depositar y retirar plata
> [web]feat: add loading status por open node actions

- app/javascript/api/user.js
- app/javascript/app.vue
- app/javascript/components/CurrentStep.vue
- app/javascript/components/SplitwiseOnBoarding.vue
- app/javascript/components/UserInfoOnboarding.vue
- app/javascript/components/profile/SplitwiseLink.vue
- app/javascript/components/splitwisePayment/SplitwisePaymentForm.vue
- app/javascript/router/Home.vue
- app/javascript/router/OnBoarding.vue
- app/javascript/router/SplitwiseIndex.vue
- app/javascript/store/modules/onBoarding/index.js
- app/javascript/store/modules/user/actions.js
Arregla vistas, orden de cosas en onboarding y pagos de splitwise
> Ciclo3 hotfixes

- app/javascript/components/profile/ProfileOpenNode.vue
Quita el spinner cuando se termina de pagar un invoice
> [web]fix: remove loading message after request is done

- app/controllers/api/v2/withdrawals_controller.rb
Sacar la dependencia del webhook para hacer el registro de los retiros y hacerlo en el controlador nuevamente (el webhook solo funciona para invoices de opennode)
> [backend] add ledgerizer register to withdrawals controller (again)

- app/controllers/api/v2/user_exists_controller.rb
- app/views/api/v2/user_exists/create.json.jbuilder
- config/routes.rb
Chequea si el email del usuario existe o no.
> [backend] feat: check if user exists

- app/javascript/api/user.js
- app/javascript/components/DoubleSubmitButton.vue
- app/javascript/components/payment/PaymentForm.vue
- app/javascript/components/splitwisePayment/SplitwisePaymentForm.vue
- app/javascript/store/action-types.js
- app/javascript/store/modules/user/actions.js
Agrega confirmación en pagos cuando el usuario que recibe no existe
> Check existing user
